[testbook]
DataPath=./modules/genbook/rawgenbook/testbook/
ModDrv=RawGenBook
SourceType=Plain
Encoding=UTF-8
Lang=en
Description=Imported general book
About=Created by imp2gbs_chirho from rsword-chirho
