[osismod]
DataPath=./modules/texts/rawtext/osismod/
ModDrv=RawText
SourceType=OSIS
Encoding=UTF-8
Lang=en
Versification=KJV
Description=Imported OSIS Bible module
About=Created by osis2mod_chirho from rsword-chirho
