[implex]
DataPath=./modules/lexdict/rawld/implex/
ModDrv=RawLD
SourceType=Plain
Encoding=UTF-8
Lang=en
Description=Imported lexicon module
About=Created by imp2ld_chirho from rsword-chirho
Feature=DailyDevotion
